# @package _global_

defaults:
  - /robots: airbot_play

demonstrator:
  _target_: airdc.common.demonstrators.grouped.GroupedDemonstrator
  auto_control:
    groups: []
  components:
    groups:
      - /
      - /
      - /
    names:
      - ""
      - follow_camera
      - env_camera
    instances:
      - "${merge_cfg:${robots}, {port: 50051}}"
      - _target_: airdc.common.devices.cameras.intelrealsense.IntelRealSenseCamera
      - _target_: airdc.common.devices.cameras.v4l2.V4L2Camera
    roles:
      - l
      - o

dataset:
  directory: airbot_play
