# @package _global_

defaults:
  - /robots: airbot_play_xbox

dataset:
  directory: xbox_force
demonstrator:
  _target_: airdc.common.demonstrators.grouped.GroupedDemonstrator
  auto_control:
    groups: []
  components:
    groups:
      - /
      - /
      - /
    names:
      - lead
      - follow
      - env_camera
    instances:
      - "${merge_cfg:${robots}, {port: 50050}}"
      - "${merge_cfg:${robots}, {port: 50051}}"
      - _target_: airdc.common.devices.cameras.v4l2.V4L2Camera
    roles:
      - l
      - f
      - o
