# @package _global_

defaults:
  - basis

demonstrator:
  components:
    groups:
      - /
    names:
      - base
    instances:
      - _target_: airbot_ie.robots.slamtec_athena2.SlamtecAthena2
        blocking: false
        rate: 50
    roles:
      - l
