# @package _global_

defaults:
  - basis

concur_inst: airdc.common.systems.wrappers.concurrent_instantiate

demonstrator:
  components:
    groups:
      - /
      - /
    names:
      - env_camera
      - follow_camera
    instances:
      - _target_: ${concur_inst}
        interface_cls: airdc.common.devices.cameras.intelrealsense.IntelRealSenseCamera
        camera_index: null
        height: 480
        width: 640
        enable_depth: true
        align_depth: true
        fps: 30
      - _target_: ${concur_inst}
        interface_cls: airdc.common.devices.cameras.v4l2.V4L2Camera
    roles:
      - o
      - o
dataset:
  directory: concur_camera
